my_string = input ('Введите любой текст: ')
print(type(my_string))
print(len(my_string))
my_string_upper = my_string.upper()
print(my_string_upper)
my_string_lower = my_string.lower()
print(my_string_lower)
my_string_replace = my_string.replace(' ','')
print(my_string_replace)
print(my_string [0])
print(my_string [-1])